spring.application.name=AI-Voice-Organizer
telegram.bot.token = 8790876599:AAHxBHmzjG_vnrV9HzhP8YICraQq7guY3bk
stt.url = http://127.0.0.1:8081/inference
llm.url = http://localhost:1234/v1/chat/completions
